version: "3.3"

services:
    # Mysql container
  mysql:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: recipes
      MYSQL_USER: php
      MYSQL_PASSWORD: php
      MYSQL_ROOT_PASSWORD: recipesapp
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - mynet

  # PHP-FPM container
  myphp:
    image: php:7.4-fpm
    ports:
      - "9000:9000"
    volumes:
      - $HOME/recipes/src:/var/www/html
    depends_on:
      - mysql
    build:
        context: $HOME/recipes/php
        dockerfile: Dockerfile
    networks:
      - mynet
  
  #Nginx container
  mynginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - $HOME/recipes/src:/var/www/html
      - $HOME/recipes/nginx/nginx.ini:/etc/nginx/conf.d/default.conf
    depends_on:
      - myphp
      - mysql
    networks:
      - mynet

  # phpMyAdmin container
  phpMyAdmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
    networks:
      - mynet

volumes:
  database: {}

networks:
  mynet:
    driver: bridge
